### ISSUE TITLE
Back up zero byte

### ISSUE THREAD

**Issue by BPouet** [sethgoldin/davinci-resolve-postgresql-workflow-tools#21]
I have install the script on 2 different servers.

One is working perfectly fine ( Mac osx with davinci 15)
The other only create zero byte backup. ( Mac osx davinci 16)

I can't find the reason why.
The password and db is ok. 
I check .pgpass
I add the "TRUST" in .conf

is there also a way to backup multiple database?

Cheers!

-BP

**Comment by sethgoldin** [comment]
Make sure that `pg_hba.conf` has the correct static IP address for the machine. I've seen several different users enter the incorrect IP address there, which caused the script will spit out zero-byte `.backup` files.

You can indeed run the script for different databases on the same system. Just run it as many times as you need.

**Comment by BPouet** [comment]
Thanks for the quick tip!
