### ISSUE TITLE
Change time of backup

### ISSUE THREAD

**Issue by paulc-us** [sethgoldin/davinci-resolve-postgresql-workflow-tools#24]
I installed the script early in the morning, to run every 24 hours, but every day it seems to start a little later, where it now runs in the middle of the day, causing issues for people using the db. How do I adjust the time?

**Comment by sethgoldin** [comment]
Are you on macOS or Linux?

If macOS, you can actually go modify the `launchd` `.plist` file directly, and use `StartCalendarInterval`

[The man page is here, on macOS.](x-man-page://launchd.plist)

On Linux, you'd [modify the systemd timer](https://wiki.archlinux.org/title/Systemd/Timers#Realtime_timer).
