### ISSUE TITLE
illegal time format

### ISSUE THREAD

**Issue by nicolasforest** [sethgoldin/davinci-resolve-postgresql-workflow-tools#38]
We've tested this on 2 differents workstation with the Resolve DB server installed and we are getting a illegal time format error when running sudo sh macos-install.sh

Any idea why?
<img width="832" alt="Capture d’écran, le 2023-08-18 à 10 13 42" src="https://github.com/sethgoldin/davinci-resolve-postgresql-workflow-tools/assets/35945288/02053855-e61b-441c-ade8-4c35bf32d55e">

**Comment by sethgoldin** [comment]
What version of macOS is this? The fact that you're seeing an error on line 1 leads me to believe you have some kind of misconfiguration with the `bash` that's installed.

**Comment by nicolasforest** [comment]
Hi the Os of both station are Monterey or Ventura. They both give me that error.

**Comment by sethgoldin** [comment]
Can you record a [Loom](https://www.loom.com/) of what it looks like when you attempt to run the script?

**Comment by sethgoldin** [comment]
You might also consider substituting `bash` for `sh`. In other words, try running `sudo bash macos-install.sh`.

**Comment by nicolasforest** [comment]
Hi sorry it took some time for me to test it again, but substituing the sh for bash isn't working. I'm having the same issue.
There is nothing to record with Loom. This is what I'm getting:

nicolasforest@Mac-mini-de-Nicolas Downloads % sudo bash macos-install.sh
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
macos-install.sh: line 1: payload:allShortcutsEnabled:false: command not found

**Comment by nicolasforest** [comment]
ok my bad! I've been able to make it work. Terminal didn't had Full disk access in MacOs Security.
