### ISSUE TITLE
Running on Sonoma? 

### ISSUE THREAD

**Issue by tjmacsindustries** [sethgoldin/davinci-resolve-postgresql-workflow-tools#42]
Hi There, I was so excited to find these scripts! Thanks for all the hard work! My server, though was on Sonoma by the time I found them. I've tried running them, but nothing seems to happen. The install looks to finish properly, but nothing shows up in the logs, except when I uninstall. That shows up as you would expect. Any ideas? Thanks a bunch!!!

![Screenshot 2024-10-07 at 5 25 02 PM](https://github.com/user-attachments/assets/31a269a7-df74-4bfe-8142-4e9829850236)

**Comment by sethgoldin** [comment]
Copy and paste here all your text in Terminal, redacting anything if
necessary. The most common cause of issues like this is some sort of
malformed path.
